fix hydration error
caused by html tags nested under a <p> tag:

Error: Hydration failed because the initial UI does not match what was rendered on the server.  Warning: Expected server HTML to contain a matching <ul> in <p>.  See more info here: https://nextjs.org/docs/messages/react-hydration-error